In [194]:
import pandas as pd
import geopandas as gpd

In [195]:
url = 'https://admin.opendata.az/dataset/74727856-3e72-4d49-ab34-9d4aac8f4ab0/resource/f0bccfe6-0639-46a7-8cfe-7e5f1be741d8/download/movcud-zolaqlar-velo.kmz'

gpd.list_layers(url)

              name geometry_type
0    VELO YOL 2026       Unknown
1  Mövcud zolaqlar       Unknown

In [196]:
gdf = gpd.read_file(url, layer='Mövcud zolaqlar')

In [197]:
gdf.head()
gdf_metr = gdf.to_crs(epsg=32639)

In [198]:
#1
sum = 0.0
for path in gdf_metr.length:
    sum += path

print(round(sum/1000,2))

57.14

In [199]:
gdf_metr['length'] = gdf_metr.length

In [200]:
max = gdf_metr.length.max()
gdf_metr[gdf_metr.length == max]

,id,Name,description,timestamp,begin,end,altitudeMode,tessellate,extrude,visibility,drawOrder,icon,geometry,length
28,None,8 Noyabr pr.,None,NaT,NaT,NaT,None,1,0,-1,NaN,None,"LINESTRING Z (410579.389 4468351.995 0, 410544...",7607.438824

In [201]:
gdf_metr.Name.value_counts()

Name
8 Noyabr pr.                                 3
Hüseyn Cavid pr.                             2
28 may HUB                                   2
Kövkəb Xanım Səfərəliyeva küç.               2
Üzeyir Hacıbəyli küç.                        2
Xəqani Rüstəmov küç.                         2
Filarmoniya bağı.                            1
İstiqlaliyyət küç.                           1
Azərbaycan pr.                               1
Mirzəağa Əliyev küç.                         1
Bəxtiyar Vahabzadə küç.                      1
Şəmsi Bədəlbəyli küç.                        1
Məmməd Rahim küç.                            1
Parlament pr.                                1
Bülbül pr.                                   1
Azadlıq pr.                                  1
28 may küç.                                  1
Abdulla Şaiq küçəsi                          1
Dilarə Əliyeva küç.                          1
Fikrət Əmirov küç.                           1
Sahil bağı                                   1
Akademik Zərifə Əliyeva küç.                 1
Nizami küç.                                  1
Xəqani küç.                                  1
Yusif Səfərov küç.                           1
Həmid Abbasbəyli küç.                        1
İzzət Orucova küç.                           1
Fəzail Bayramov küç.                         1
Ağ şəhər ərazisi.                            1
Afiyəddin Cəlilov küç.                       1
Nəcəfqulu Rəfiyev küç.                       1
Neftçilər pr-Bulvar                          1
Crescent mall ərazisi                        1
Xocalı pr.                                   1
Ağ şəhər bulvarı ərazisi                     1
Aleksandr Puşkin küç.                        1
Şıxəli Qurbanov küçəsi                       1
Xaqani küçəsi                                1
İnşaatçılar pr.                              1
Mikayıl Müşviq küç.                          1
Cəfər Cabbarlı küçəsi                        1
Xətai pr.                                    1
Üzeyir H - Keykab S. - keçid                 1
Əbdürrəhim bəy Haqverdiyev küçəsi            1
Əziz Əliyev küç.                             1
Bulvar                                       1
Mətbuat pr.                                  1
Bulvar 2                                     1
Vaqif pr.                                    1
Keykab xanım Səfərəliyeva 2                  1
Şəfayət Mehdiyev küç.                        1
Rəşid Behbudov küç.                          1
Fəzail Bayramov küç. - Yusif Səfərov küç.    1
Xan Şuşinski                                 1
Name: count, dtype: int64

In [202]:
url_parkings = 'https://admin.opendata.az/dataset/8d61b508-7f13-4219-984f-08d769c61251/resource/6902ae9f-e2ae-4c20-bdee-6fd55c701645/download/mpv-v-mps.-son.kmz'
layers = gpd.list_layers(url_parkings)
print(layers)
parkings_df = gpd.read_file(url_parkings, layer ='velosiped məntəqələri yeni')

                                      name geometry_type
0                         Temporary Places       Unknown
1    velosiped məntəqələri.11 sentyabr.kmz       Unknown
2  Velosiped yolları 2025. avqust. son.kmz       Unknown
3            Velosiped yolları 2025 yanvar       Unknown
4              Ümumi 12 iyul. SON olan.kmz       Unknown
5                                My Places       Unknown
6                         Sightseeing Tour       Unknown
7               velosiped məntəqələri yeni       Unknown

In [203]:
points_m = gpd.GeoSeries(parkings_df.geometry, crs = gdf.crs).to_crs(epsg=32639)

In [204]:
i = 0
for point in points_m:
    if (gdf_metr.geometry.distance(point) <= 50.0).sum() > 0:
        i = i +1
print(i)

87

In [217]:
arr = parkings_df[~((parkings_df.geometry.x > 49.70) & (parkings_df.geometry.x < 50.05) & (parkings_df.geometry.y > 40.30) & (parkings_df.geometry.y < 40.46))]

print(f'{len(arr)}: {", ".join(arr.Name)}')

4: MPV-144-2, MPV-145-2, MPV-146-2, MPV-147-2

In [226]:
arr[['geometry']]

                          geometry
143  POINT Z (49.98242 40.59187 0)
144  POINT Z (49.97011 40.58852 0)
145  POINT Z (49.93778 40.57854 0)
146  POINT Z (49.93628 40.58281 0)